services:
  db:
    image: postgres:16
    container_name: batala_vitrine_db
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      # - db_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: batala_vitrine_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@batala.fr
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: unless-stopped

# volumes:
#   db_data:
